header:
  version: 11

defaults:
  repos:
    refspec: kirkstone

machine: stm32mp1

distro: poky

target: core-image-fdrc

repos:
  poky:
    url: "https://git.yoctoproject.org/poky"
    layers:
      meta:
      meta-poky:

  meta-openembedded:
    url: "https://git.openembedded.org/meta-openembedded"
    layers:
      meta-networking:
      meta-oe:
      meta-python:

  meta-st-stm32mp:
    url: "https://github.com/STMicroelectronics/meta-st-stm32mp"

  meta-fdrc:
    url: "git@gitlab.kelle.grp:caspar.friedrich/meta-fdrc.git"
    refspec: main

  # Required by `meta-browser`
  # Todo: Remove if no longer required
  meta-clang:
    url: "https://github.com/kraj/meta-clang.git"

  # Required for `gn-native`
  # Todo: Extract reqcipe
  meta-browser:
    url: "https://github.com/OSSystems/meta-browser.git"
    refspec: master
    layers:
      meta-chromium:

  # Requires `gn-native`
  meta-matter:
    url: "https://github.com/NXPmicro/meta-matter.git"
    refspec: master

local_conf_header:
  defaults: |
    DISTRO_FEATURES:append = " bluetooth wifi systemd "
    DISTRO_FEATURES_BACKFILL_CONSIDERED = "sysvinit"
    EXTRA_IMAGE_FEATURES:append = " debug-tweaks "
    VIRTUAL-RUNTIME_init_manager = "systemd"
    VIRTUAL-RUNTIME_initscripts = ""
